### ISSUE TITLE
如何获取咪咕UID和咪咕Token

### ISSUE THREAD

**Issue by malou8** [FanchangWang/allinone_format#10]
如何获取咪咕UID和咪咕Token？

**Comment by FanchangWang** [comment]
这是 allinone 的教程部分，与 allinone_format 无关，具体请在下面中寻找。

allinone
官方讨论组
https://t.me/feiyangdigital
在线文档
https://pan.v1.mk/%E6%AF%8F%E6%9C%9F%E8%A7%86%E9%A2%91%E4%B8%AD%E7%94%A8%E5%88%B0%E7%9A%84%E6%96%87%E4%BB%B6%E5%88%86%E4%BA%AB/allinone%E4%BA%8C%E8%BF%9B%E5%88%B6%E6%96%87%E4%BB%B6/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md
