### ISSUE TITLE
有openwrt的脚本吗？

### ISSUE THREAD

**Issue by 77160860** [FanchangWang/allinone_format#11]
allinone直接用二进制跑在openwrt里面了，没docker

**Comment by FanchangWang** [comment]
那你只需要安装 allinone_format docker 容器就行了，用法是一样的。

配置页面里面正确填写 allInone 的 http://内网IP:端口/tv.m3u 地址就可以了。

**Comment by 77160860** [comment]
> 那你只需要安装 allinone_format docker 容器就行了，用法是一样的。
> 
> 配置页面里面正确填写 allInone 的 [http://内网IP:端口/tv.m3u](http://%E5%86%85%E7%BD%91IP:%E7%AB%AF%E5%8F%A3/tv.m3u) 地址就可以了。

内存太小 装不了docker

**Comment by FanchangWang** [comment]
我这个是基于 php 实现的，如果你 openwrt 上有 php 环境的话也可以考虑直接运行 php 代码。

如果 php 环境也没有的话，那你大概率没法在 openwrt 上直接使用 allInone_format 了。
