### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by gc89925** [FanchangWang/allinone_format#12]
# 将 /path/to/config/ 改为你的配置文件存放目录
这一句什么意思，能不能举个例子，我是openwrt软路由，这个具体怎么改？
我直接复制下面这条命令，也装好了，就是不知道对不对
docker run -d --restart=unless-stopped --pull=always --net=host -v /path/to/config/:/app/config/ -p 35456:35456 --name allinone_format yuexuangu/allinone_format:latest

**Comment by gc89925** [comment]
> docker run -d --restart=unless-stopped --pull=always --net=host -v /opt/config/:/app/config/ -p 35456:35456 --name allinone_format yuexuangu/allinone_format:latest

我的Docker根目录是：
/mnt/nvme0n1-4/docker

**Comment by gc89925** [comment]
> docker run -d --restart=unless-stopped --pull=always --net=host -v /mnt/nvme0n1-4/docker/allinone_format/:/app/config/ -p 35456:35456 --name allinone_format yuexuangu/allinone_format:latest

好的，谢谢大佬

**Comment by gc89925** [comment]
> docker run -d --restart=unless-stopped --pull=always --net=host -v /mnt/nvme0n1-4/docker/allinone_format/:/app/config/ -p 35456:35456 --name allinone_format yuexuangu/allinone_format:latest

root@iStoreOS:~# docker run -d --restart=unless-stopped --pull=always --net=host -v /mnt/nvme0n1-4/docker/allinone_format/:/app/config/ -p 35456:35
456 --name allinone_format yuexuangu/allinone_format:latest
latest: Pulling from yuexuangu/allinone_format
Digest: sha256:ac0228cdb020b131ed65a20049759648d9c60ca3d336d258c2b8bbe78cc83983
Status: Image is up to date for yuexuangu/allinone_format:latest
WARNING: Published ports are discarded when using host network mode
adb7a125b9c173ec3f58e1f7fa81bf1abdc6f0fb0a0c762f3a5c5932da45e61b

**Comment by FanchangWang** [comment]
就是警告 -p 参数无效了，因为 host 模式会自动映射。不影响，你看看运行的容器列表里应该已经有了。

**Comment by gc89925** [comment]
> 就是警告 -p 参数无效了，因为 host 模式会自动映射。不影响，你看看运行的容器列表里应该已经有了。

嗯嗯，是正常运行了，感觉跟之前装好的没啥区别。

http://192.168.100.1:35456/m3u/2
这个地址在Windows的potPlayer里面无法聚合吗？我去TV端软件里面试试

**Comment by FanchangWang** [comment]
potplayer 软件不支持聚合功能

**Comment by gc89925** [comment]
安卓tv的tvtimate可以支持吗？还有，大佬有没有电报群之类的？

**Comment by gc89925** [comment]
好的大佬，谢谢这么晚还回复。
