### ISSUE TITLE
你好  我现在是安装在群晖里面  更新后出现了   这个问题启动不了  

### ISSUE THREAD

**Issue by wangxiaoxiong228** [FanchangWang/allinone_format#13]
![Uploading QQ图片20241224004431.png…]()
希望你看看怎么解决

**Comment by wangxiaoxiong228** [comment]
![Uploading QQ图片20241224004431.png…]()

**Comment by wangxiaoxiong228** [comment]
图片上传不上去   
connecting to 
127.0.0.1:35456(127.0.0.1:353456) wget:server returned error:HTTP/1.1 404 Not Found

**Comment by FanchangWang** [comment]
你上传的图片似乎有问题，我这边看不到图片内容

**Comment by wangxiaoxiong228** [comment]
![QQ图片20241224004431](https://github.com/user-attachments/assets/b768045d-4b8d-434f-9edb-8b074505052b)

**Comment by FanchangWang** [comment]
你不能使用 127.0.0.1，应该使用内网 ip ，比如 192.168. 开头的

**Comment by wangxiaoxiong228** [comment]
怎么设置呢：？

**Comment by wangxiaoxiong228** [comment]
没更新前一直正常使用呀

**Comment by wangxiaoxiong228** [comment]
![QQ截图20241224005653](https://github.com/user-attachments/assets/d3f99a51-60a9-49f3-904d-a53c02471250)

**Comment by FanchangWang** [comment]
你这个是容器内部的 php 服务器启动失败了，你之前如果安装过的话。这里不应该失败啊。你可以尝试删除容器跟镜像，重新拉取安装试试

**Comment by FanchangWang** [comment]
或者你也可以尝试使用 host 网络试试

**Comment by wangxiaoxiong228** [comment]
好的   我在拉取一次试试    host  我也试过了  不行



> 你这个是容器内部的 php 服务器启动失败了，你之前如果安装过的话。这里不应该失败啊。你可以尝试删除容器跟镜像，重新拉取安装试试

**Comment by FanchangWang** [comment]
![Screenshot_2024-12-24-01-00-41-658_com.microsoft.emmx-edit.jpg](https://github.com/user-attachments/assets/1fceb49a-8896-4bef-b5c9-265a37b11923)

这里的容器日志应该能看出更多的问题详情。

**Comment by FanchangWang** [comment]
而且我仔细看了一下，你这个镜像不是新版本的，是很早之前的旧版本了。

**Comment by FanchangWang** [comment]
新版本的执行命令跟你这个版本参数不同

**Comment by wangxiaoxiong228** [comment]
哎，我在群晖里面更新的 最新呀  - -   大佬

**Comment by FanchangWang** [comment]
大概是你没有重新拉取 docker 镜像导致的。你把容器跟镜像都删了，重新拉取大概率就好了

**Comment by wangxiaoxiong228** [comment]
大佬辛苦了    耐心的 讲解   谢谢 你

**Comment by FanchangWang** [comment]
解决了就好
