### ISSUE TITLE
没办法使用域名请求数据了

### ISSUE THREAD

**Issue by wenxian11111** [FanchangWang/allinone_format#4]
链接h=域名，无法请求参数，但是使用局域网ip就可以，问题来了只能在局域网播放，没有办法在外面也使用这个地址。单独请求肥羊m3u是能下载文件的

**Comment by FanchangWang** [comment]
我之前没考虑域名的事，我稍后改改代码吧，直接增加个 tvurl=https://域名/tv.m3u 这样的参数，可以直接传肥猫的请求链接，一劳永逸

**Comment by FanchangWang** [comment]
allinone_format 镜像 dev 开发版已推送，你可以测试下看看，支持直接配置完整 allinone tv.m3u 访问链接，同时这个还支持 三种 m3u 格式，三种 txt 格式。

不挂载配置文件使用这个
`docker run -d --restart=unless-stopped -p 35456:35456 --name allinone_format yuexuangu/allinone_format:dev`

挂载 config 配置文件使用这个
`docker run -d --restart=unless-stopped -v /path/to/config/:/app/config/ -p 35456:35456 --name allinone_format yuexuangu/allinone_format:dev`

直接访问 http://ip:35456/ 就可以进入配置界面。

![image](https://github.com/user-attachments/assets/4da74d05-c71c-4d7c-a5c6-588ceb8ffb87)

**Comment by FanchangWang** [comment]
https://github.com/FanchangWang/allinone_format/commit/f76fb64edce4ba1c6574f75e1c96f4d056d04f97 重构代码已提交，此 pr 的功能在重构代码已实现。请使用新的 docker 命令拉取镜像，然后在配置页面进行设置使用。
