### ISSUE TITLE
tv.m3u 地址无法访问: http://192.168.0.222:35455/tv.m3u

### ISSUE THREAD

**Issue by josbu** [FanchangWang/allinone_format#8]
tv.m3u 地址无法访问: http://[192.168.0.222](http://192.168.0.222:35455/tv.m3u):35455/tv.m3u   报错这个

![image](https://github.com/user-attachments/assets/b881b4c2-dfa3-4f9b-858c-8e756c88cf91)

**Comment by FanchangWang** [comment]
请按以下方式进行排查

1. 排查链接的可用性。方法：用浏览器访问 http://192.168.0.222:35455/tv.m3u 看看会不会触发下载 tv.m3u 
2. 排查容器的网络。方法：部署 allinone_format 容器的时候，使用 --net=host 网络参数，看看是否能解决问题
3. 排查是否是代码错误。方法：检查 allinone_format 容器的执行日志，检查日志中是否有错误信息输出。

**Comment by FanchangWang** [comment]
如果 allinone_format 容器日志有错误，可以将错误日志贴上来，我看看是什么引起的。

**Comment by josbu** [comment]
> * 排查链接的可用性。方法：用浏览器访问 http://192.168.0.222:35455/tv.m3u 看看会不会触发下载 tv.m3u   ------不会下载
> * 排查容器的网络。方法：部署 allinone_format 容器的时候，使用 --net=host 网络参数，看看是否能解决问题     ---- 反复几次一样的症状
> * 排查是否是代码错误。方法：检查 allinone_format 容器的执行日志，检查日志中是否有错误信息输出。
日志：[Sun Dec  8 15:58:17 2024] PHP 8.3.14 Development Server (http://0.0.0.0:35456) started
[Sun Dec  8 15:58:46 2024] 192.168.0.16:2362 Accepted
[Sun Dec  8 15:58:46 2024] [INFO] GET /
[Sun Dec  8 15:58:46 2024] 192.168.0.16:2362 Closing
[Sun Dec  8 15:58:47 2024] 192.168.0.16:2363 Accepted
[Sun Dec  8 15:58:47 2024] 192.168.0.16:2364 Accepted
[Sun Dec  8 15:58:47 2024] [INFO] GET /assets/index-c_dY7tvU.css
[Sun Dec  8 15:58:47 2024] 192.168.0.16:2363 Closing
[Sun Dec  8 15:58:47 2024] [INFO] GET /assets/index-CcgpMEUs.js
[Sun Dec  8 15:58:47 2024] 192.168.0.16:2364 Closing
[Sun Dec  8 15:58:47 2024] 127.0.0.1:53328 Accepted
[Sun Dec  8 15:58:47 2024] [INFO] GET /favicon.ico
[Sun Dec  8 15:58:47 2024] 127.0.0.1:53328 Closing
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2369 Accepted
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2370 Accepted
[Sun Dec  8 15:58:48 2024] [INFO] GET /api/config
[Sun Dec  8 15:58:48 2024] [ERROR] tv_m3u_url 订阅源必须设置
[Sun Dec  8 15:58:48 2024] [DEBUG] 尝试检测 tv.m3u url: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:58:48 2024] [DEBUG] Fetching URL: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:58:48 2024] [ERROR] Fetch content failed: CURL Error: Failed to connect to 192.168.0.222 port 35455 after 0 ms: Could not connect to server
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2369 Closing
[Sun Dec  8 15:58:48 2024] [INFO] GET /api/channel-urls
[Sun Dec  8 15:58:48 2024] [ERROR] tv_m3u_url 订阅源必须设置
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2370 Closing
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2375 Accepted
[Sun Dec  8 15:58:48 2024] [INFO] GET /assets/materialdesignicons-webfont-Dp5v-WZN.woff2?v=7.4.47
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2375 Closing
[Sun Dec  8 15:59:04 2024] 192.168.0.16:2393 Accepted
[Sun Dec  8 15:59:04 2024] [INFO] POST /api/config
[Sun Dec  8 15:59:04 2024] [ERROR] tv_m3u_url 订阅源必须设置
[Sun Dec  8 15:59:04 2024] [DEBUG] Fetching URL: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:59:04 2024] [ERROR] Fetch content failed: CURL Error: Failed to connect to 192.168.0.222 port 35455 after 0 ms: Could not connect to server
[Sun Dec  8 15:59:04 2024] [ERROR] 更新配置失败: tv.m3u 地址无法访问: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:59:04 2024] 192.168.0.16:2393 Closing
[Sun Dec  8 15:59:07 2024] 192.168.0.16:2394 Accepted
[Sun Dec  8 15:59:07 2024] [INFO] POST /api/config
[Sun Dec  8 15:59:07 2024] [ERROR] tv_m3u_url 订阅源必须设置
[Sun Dec  8 15:59:07 2024] [DEBUG] Fetching URL: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:59:07 2024] [ERROR] Fetch content failed: CURL Error: Failed to connect to 192.168.0.222 port 35455 after 0 ms: Could not connect to server
[Sun Dec  8 15:59:07 2024] [ERROR] 更新配置失败: tv.m3u 地址无法访问: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:59:07 2024] 192.168.0.16:2394 Closing
[Sun Dec  8 15:59:17 2024] 127.0.0.1:40184 Accepted
[Sun Dec  8 15:59:17 2024] [INFO] GET /favicon.ico
[Sun Dec  8 15:59:17 2024] 127.0.0.1:40184 Closing

**Comment by josbu** [comment]
> * 排查链接的可用性。方法：用浏览器访问 http://192.168.0.222:35455/tv.m3u 看看会不会触发下载 tv.m3u   ------不会下载
> * 排查容器的网络。方法：部署 allinone_format 容器的时候，使用 --net=host 网络参数，看看是否能解决问题     ---- 反复几次一样的症状
> * 排查是否是代码错误。方法：检查 allinone_format 容器的执行日志，检查日志中是否有错误信息输出。
日志：[Sun Dec  8 15:58:17 2024] PHP 8.3.14 Development Server (http://0.0.0.0:35456) started
[Sun Dec  8 15:58:46 2024] 192.168.0.16:2362 Accepted
[Sun Dec  8 15:58:46 2024] [INFO] GET /
[Sun Dec  8 15:58:46 2024] 192.168.0.16:2362 Closing
[Sun Dec  8 15:58:47 2024] 192.168.0.16:2363 Accepted
[Sun Dec  8 15:58:47 2024] 192.168.0.16:2364 Accepted
[Sun Dec  8 15:58:47 2024] [INFO] GET /assets/index-c_dY7tvU.css
[Sun Dec  8 15:58:47 2024] 192.168.0.16:2363 Closing
[Sun Dec  8 15:58:47 2024] [INFO] GET /assets/index-CcgpMEUs.js
[Sun Dec  8 15:58:47 2024] 192.168.0.16:2364 Closing
[Sun Dec  8 15:58:47 2024] 127.0.0.1:53328 Accepted
[Sun Dec  8 15:58:47 2024] [INFO] GET /favicon.ico
[Sun Dec  8 15:58:47 2024] 127.0.0.1:53328 Closing
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2369 Accepted
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2370 Accepted
[Sun Dec  8 15:58:48 2024] [INFO] GET /api/config
[Sun Dec  8 15:58:48 2024] [ERROR] tv_m3u_url 订阅源必须设置
[Sun Dec  8 15:58:48 2024] [DEBUG] 尝试检测 tv.m3u url: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:58:48 2024] [DEBUG] Fetching URL: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:58:48 2024] [ERROR] Fetch content failed: CURL Error: Failed to connect to 192.168.0.222 port 35455 after 0 ms: Could not connect to server
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2369 Closing
[Sun Dec  8 15:58:48 2024] [INFO] GET /api/channel-urls
[Sun Dec  8 15:58:48 2024] [ERROR] tv_m3u_url 订阅源必须设置
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2370 Closing
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2375 Accepted
[Sun Dec  8 15:58:48 2024] [INFO] GET /assets/materialdesignicons-webfont-Dp5v-WZN.woff2?v=7.4.47
[Sun Dec  8 15:58:48 2024] 192.168.0.16:2375 Closing
[Sun Dec  8 15:59:04 2024] 192.168.0.16:2393 Accepted
[Sun Dec  8 15:59:04 2024] [INFO] POST /api/config
[Sun Dec  8 15:59:04 2024] [ERROR] tv_m3u_url 订阅源必须设置
[Sun Dec  8 15:59:04 2024] [DEBUG] Fetching URL: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:59:04 2024] [ERROR] Fetch content failed: CURL Error: Failed to connect to 192.168.0.222 port 35455 after 0 ms: Could not connect to server
[Sun Dec  8 15:59:04 2024] [ERROR] 更新配置失败: tv.m3u 地址无法访问: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:59:04 2024] 192.168.0.16:2393 Closing
[Sun Dec  8 15:59:07 2024] 192.168.0.16:2394 Accepted
[Sun Dec  8 15:59:07 2024] [INFO] POST /api/config
[Sun Dec  8 15:59:07 2024] [ERROR] tv_m3u_url 订阅源必须设置
[Sun Dec  8 15:59:07 2024] [DEBUG] Fetching URL: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:59:07 2024] [ERROR] Fetch content failed: CURL Error: Failed to connect to 192.168.0.222 port 35455 after 0 ms: Could not connect to server
[Sun Dec  8 15:59:07 2024] [ERROR] 更新配置失败: tv.m3u 地址无法访问: http://192.168.0.222:35455/tv.m3u
[Sun Dec  8 15:59:07 2024] 192.168.0.16:2394 Closing
[Sun Dec  8 15:59:17 2024] 127.0.0.1:40184 Accepted
[Sun Dec  8 15:59:17 2024] [INFO] GET /favicon.ico
[Sun Dec  8 15:59:17 2024] 127.0.0.1:40184 Closing

**Comment by FanchangWang** [comment]
从你这个排查结果来看，我怎么感觉你这是 allinone 这个前置项目没部署或者部署的有问题？明显是无法正常访问的状态。

你可以重新检查 allinone 容易的部署是否有问题，保证浏览器访问的时候可以触发 tv.m3u 文件的下载才行。

**Comment by josbu** [comment]
> 从你这个排查结果来看，我怎么感觉你这是 allinone 这个前置项目没部署或者部署的有问题？明显是无法正常访问的状态。
> 
> 你可以重新检查 allinone 容器的部署是否有问题，保证浏览器访问的时候可以触发 tv.m3u 文件的下载才行。

应该 是 哪个是前置项目， 我有点不明白 我去看看你的项目去

**Comment by FanchangWang** [comment]
allinone项目文档地址，请参考这个。如果还不懂也可以加这个项目的 tg 频道进行问询。

https://pan.v1.mk/%E6%AF%8F%E6%9C%9F%E8%A7%86%E9%A2%91%E4%B8%AD%E7%94%A8%E5%88%B0%E7%9A%84%E6%96%87%E4%BB%B6%E5%88%86%E4%BA%AB/allinone%E4%BA%8C%E8%BF%9B%E5%88%B6%E6%96%87%E4%BB%B6/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md

**Comment by FanchangWang** [comment]
allinone项目的官方 tg 讨论组

https://t.me/feiyangdigital

**Comment by josbu** [comment]
解决了
