### ISSUE TITLE
能否在分组中单独增加某些直播源地址

### ISSUE THREAD

**Issue by kiko923** [FanchangWang/allinone_format#9]
可以自定义添加某些直播源到自己的分组

**Comment by FanchangWang** [comment]
主要是我个人没这需求，所以没啥太大的动力去实现这个功能。。。

而且手上还有其他要搞的东西，我最近比较倾向于先搞 pg 的 docker ，相比于看直播，我看点播更多一些，能自定义 pg 的配置优先级对我来说更高一点。

**Comment by kiko923** [comment]
希望后续有时间的话能加入此功能 非常感谢

**Comment by FanchangWang** [comment]
我尽量。。。但我不能保证啥。。。

**Comment by kiko923** [comment]
收到

**Comment by FanchangWang** [comment]
你可以使用这个项目进行多个直播源的频道管理，应该能满足你的需求。

https://github.com/taksssss/EPG-Server
